name: LoopHole
favicon: null
layout_spectrum: 0.52068
typography_spectrum: 0.80227
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#070707'
    - '#5a5a5a'
    - '#c4c4c4'
    - '#909090'
  brandStrength: 0.9375
  lightness: 0.5625
  saturation: 0.8657770452555269
  rhythmicContrast: 0.8348080178257078
purpose: []
