name: LoopHole
favicon: null
layout_spectrum: 0.393360415706411
typography_spectrum: 0.46535304212011397
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.3198592448607087
  lightness: 0.108924669213593
  saturation: 0.8657770452555269
  rhythmicContrast: 0.8348080178257078
purpose: []
